/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 21, 2017 at 6:19:00 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Library/MobileSubstrate/DynamicLibraries/GroupMe.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface GMEmptyView : UIView {

	UIImageView* _imageView;
	UILabel* _label;

}

@property (nonatomic,retain) UIImageView * imageView;              //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) UILabel * label;                      //@synthesize label=_label - In the implementation block
-(id)initWithTitle:(id)arg1 image:(id)arg2 ;
-(UIImageView *)imageView;
-(UILabel *)label;
-(void)setLabel:(UILabel *)arg1 ;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setupConstraints;
@end

