/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 2:44:28 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SZExtractorDelegate <NSObject>
@optional
-(void)setExtractionProgress:(double)arg1;
-(void)extractionCompleteAtArchivePath:(id)arg1;
-(void)extractionEnteredPassThroughMode;

@end

